



def params():
    return [
        {'atmpro': 'mls',
         'band': [1],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [1],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [1],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 300},

        {'atmpro': 'mls',
         'band': [2],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [2],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [2],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 300},

        {'atmpro': 'mls',
         'band': [3],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [3],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [3],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 300},

        {'atmpro': 'mls',
         'band': [4],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [4],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [4],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 300},

        {'atmpro': 'mls',
         'band': [5],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [5],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [5],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 300},

        {'atmpro': 'mls',
         'band': [6],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [6],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [6],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 300},

        {'atmpro': 'mls',
         'band': [7],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [7],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [7],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 300},

        {'atmpro': 'mls',
         'band': [8],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [8],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [8],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 300},

        {'atmpro': 'mls',
         'band': [9],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [9],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [9],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 300},

        {'atmpro': 'mls',
         'band': [10],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [10],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [10],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 300},

        {'atmpro': 'mls',
         'band': [11],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [11],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [11],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro'},
         'tsfc': 300},

        {'atmpro': 'mls',
         'band': [3],
         'commitnumber': 'de5d43e',
         'molecule': {'co2': 0.0004},
         'tsfc': 294},
        {'atmpro': 'mls',
         'band': [4],
         'commitnumber': 'de5d43e',
         'molecule': {'co2': 0.0004},
         'tsfc': 294},
        {'atmpro': 'mls',
         'band': [5],
         'commitnumber': 'de5d43e',
         'molecule': {'co2': 0.0004},
         'tsfc': 294},
        {'atmpro': 'mls',
         'band': [6],
         'commitnumber': 'de5d43e',
         'molecule': {'co2': 0.0004},
         'tsfc': 294},
         {'atmpro': 'mls',
          'band': [7],
          'commitnumber': 'de5d43e',
          'molecule': {'co2': 0.0004},
          'tsfc': 294},
        {'atmpro': 'mls',
         'band': [11],
         'commitnumber': 'de5d43e',
         'molecule': {'co2': 0.0004},
         'tsfc': 294},

        {'atmpro': 'mls',
         'band': [7],
         'commitnumber': 'de5d43e',
         'molecule': {'o3': 'atmpro'},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [7],
         'commitnumber': 'de5d43e',
         'molecule': {'o3': 'atmpro'},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [7],
         'commitnumber': 'de5d43e',
         'molecule': {'o3': 'atmpro'},
         'tsfc': 300},

        {'atmpro': 'mls',
         'band': [11],
         'commitnumber': 'de5d43e',
         'molecule': {'o3': 'atmpro'},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [11],
         'commitnumber': 'de5d43e',
         'molecule': {'o3': 'atmpro'},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [11],
         'commitnumber': 'de5d43e',
         'molecule': {'o3': 'atmpro'},
         'tsfc': 300},

        {'atmpro': 'mls',
         'band': [3],
         'commitnumber': 'de5d43e',
         'molecule': {'n2o': 3.2e-07},
         'tsfc': 294},
        {'atmpro': 'mls',
         'band': [9],
         'commitnumber': 'de5d43e',
         'molecule': {'n2o': 3.2e-07},
         'tsfc': 294},
        {'atmpro': 'mls',
         'band': [9],
         'commitnumber': 'de5d43e',
         'molecule': {'ch4': 1.8e-06},
         'tsfc': 294},
        {'atmpro': 'mls',
         'band': [3],
         'commitnumber': 'de5d43e',
         'molecule': {'co2': 0.0004, 'h2o': 'atmpro', 'n2o': 3.2e-07},
         'tsfc': 294},
        {'atmpro': 'mls',
         'band': [4],
         'commitnumber': 'de5d43e',
         'molecule': {'co2': 0.0004, 'h2o': 'atmpro'},
         'tsfc': 294},
        {'atmpro': 'mls',
         'band': [5],
         'commitnumber': 'de5d43e',
         'molecule': {'co2': 0.0004, 'h2o': 'atmpro'},
         'tsfc': 294},
        {'atmpro': 'mls',
         'band': [6],
         'commitnumber': 'de5d43e',
         'molecule': {'co2': 0.0004, 'h2o': 'atmpro'},
         'tsfc': 294},
        {'atmpro': 'mls',
         'band': [7],
         'commitnumber': 'de5d43e',
         'molecule': {'co2': 0.0004, 'h2o': 'atmpro', 'o3': 'atmpro'},
         'tsfc': 294},
        {'atmpro': 'mls',
         'band': [7],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro', 'o3': 'atmpro'},
         'tsfc': 294},
        {'atmpro': 'mls',
         'band': [9],
         'commitnumber': 'de5d43e',
         'molecule': {'h2o': 'atmpro', 'n2o': 3.2e-07},
         'tsfc': 294},
        {'atmpro': 'mls',
         'band': [9],
         'commitnumber': 'de5d43e',
         'molecule': {'ch4': 1.8e-06, 'h2o': 'atmpro', 'n2o': 3.2e-07},
         'tsfc': 294},
        {'atmpro': 'mls',
         'band': [11],
         'commitnumber': 'de5d43e',
         'molecule': {'co2': 0.0004, 'h2o': 'atmpro'},
         'tsfc': 294},
        {'atmpro': 'mls',
         'band': [3],
         'commitnumber': '523cbb7',
         'molecule': {'n2o': 6.4e-07},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [3],
         'commitnumber': '523cbb7',
         'molecule': {'n2o': 6.4e-07},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [3],
         'commitnumber': '523cbb7',
         'molecule': {'n2o': 6.4e-07},
         'tsfc': 300},
        {'atmpro': 'mls',
         'band': [9],
         'commitnumber': '523cbb7',
         'molecule': {'n2o': 6.4e-07},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [9],
         'commitnumber': '523cbb7',
         'molecule': {'n2o': 6.4e-07},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [9],
         'commitnumber': '523cbb7',
         'molecule': {'n2o': 6.4e-07},
         'tsfc': 300},
        {'atmpro': 'mls',
         'band': [3],
         'commitnumber': '523cbb7',
         'molecule': {'co2': 0.0004, 'h2o': 'atmpro', 'n2o': 6.4e-07},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [3],
         'commitnumber': '523cbb7',
         'molecule': {'co2': 0.0004, 'h2o': 'atmpro', 'n2o': 6.4e-07},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [3],
         'commitnumber': '523cbb7',
         'molecule': {'co2': 0.0004, 'h2o': 'atmpro', 'n2o': 6.4e-07},
         'tsfc': 300},
        {'atmpro': 'mls',
         'band': [9],
         'commitnumber': '523cbb7',
         'molecule': {'ch4': 1.8e-06, 'h2o': 'atmpro', 'n2o': 6.4e-07},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [9],
         'commitnumber': '523cbb7',
         'molecule': {'ch4': 1.8e-06, 'h2o': 'atmpro', 'n2o': 6.4e-07},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [9],
         'commitnumber': '523cbb7',
         'molecule': {'ch4': 1.8e-06, 'h2o': 'atmpro', 'n2o': 6.4e-07},
         'tsfc': 300},
        {'atmpro': 'mls',
         'band': [9],
         'commitnumber': '523cbb7',
         'molecule': {'ch4': 3.6e-06, 'h2o': 'atmpro', 'n2o': 3.2e-07},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [9],
         'commitnumber': '523cbb7',
         'molecule': {'ch4': 3.6e-06, 'h2o': 'atmpro', 'n2o': 3.2e-07},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [9],
         'commitnumber': '523cbb7',
         'molecule': {'ch4': 3.6e-06, 'h2o': 'atmpro', 'n2o': 3.2e-07},
         'tsfc': 300},
        {'atmpro': 'mls',
         'band': [9],
         'commitnumber': '523cbb7',
         'molecule': {'ch4': 3.6e-06},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [9],
         'commitnumber': '523cbb7',
         'molecule': {'ch4': 3.6e-06},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [9],
         'commitnumber': '523cbb7',
         'molecule': {'ch4': 3.6e-06},
         'tsfc': 300},
        {'atmpro': 'mls',
         'band': [9],
         'commitnumber': '523cbb7',
         'molecule': {'ch4': 1.8e-06},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [9],
         'commitnumber': '523cbb7',
         'molecule': {'ch4': 1.8e-06},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [9],
         'commitnumber': '523cbb7',
         'molecule': {'ch4': 1.8e-06},
         'tsfc': 300},
        {'atmpro': 'mls',
         'band': [3],
         'commitnumber': '523cbb7',
         'molecule': {'n2o': 3.2e-07},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [3],
         'commitnumber': '523cbb7',
         'molecule': {'n2o': 3.2e-07},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [3],
         'commitnumber': '523cbb7',
         'molecule': {'n2o': 3.2e-07},
         'tsfc': 300},
        {'atmpro': 'mls',
         'band': [9],
         'commitnumber': '523cbb7',
         'molecule': {'n2o': 3.2e-07},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [9],
         'commitnumber': '523cbb7',
         'molecule': {'n2o': 3.2e-07},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [9],
         'commitnumber': '523cbb7',
         'molecule': {'n2o': 3.2e-07},
         'tsfc': 300},
        {'atmpro': 'mls',
         'band': [3],
         'commitnumber': '523cbb7',
         'molecule': {'co2': 0.0004},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [3],
         'commitnumber': '523cbb7',
         'molecule': {'co2': 0.0004},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [3],
         'commitnumber': '523cbb7',
         'molecule': {'co2': 0.0004},
         'tsfc': 300},
        {'atmpro': 'mls',
         'band': [4],
         'commitnumber': '523cbb7',
         'molecule': {'co2': 0.0004},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [4],
         'commitnumber': '523cbb7',
         'molecule': {'co2': 0.0004},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [4],
         'commitnumber': '523cbb7',
         'molecule': {'co2': 0.0004},
         'tsfc': 300},
        {'atmpro': 'mls',
         'band': [5],
         'commitnumber': '523cbb7',
         'molecule': {'co2': 0.0004},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [5],
         'commitnumber': '523cbb7',
         'molecule': {'co2': 0.0004},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [5],
         'commitnumber': '523cbb7',
         'molecule': {'co2': 0.0004},
         'tsfc': 300},
        {'atmpro': 'mls',
         'band': [6],
         'commitnumber': '523cbb7',
         'molecule': {'co2': 0.0004},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [6],
         'commitnumber': '523cbb7',
         'molecule': {'co2': 0.0004},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [6],
         'commitnumber': '523cbb7',
         'molecule': {'co2': 0.0004},
         'tsfc': 300},
        {'atmpro': 'mls',
         'band': [7],
         'commitnumber': '523cbb7',
         'molecule': {'co2': 0.0004},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [7],
         'commitnumber': '523cbb7',
         'molecule': {'co2': 0.0004},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [7],
         'commitnumber': '523cbb7',
         'molecule': {'co2': 0.0004},
         'tsfc': 300},
        {'atmpro': 'mls',
         'band': [11],
         'commitnumber': '523cbb7',
         'molecule': {'co2': 0.0004},
         'tsfc': 294},
        {'atmpro': 'saw',
         'band': [11],
         'commitnumber': '523cbb7',
         'molecule': {'co2': 0.0004},
         'tsfc': 257},
        {'atmpro': 'trp',
         'band': [11],
         'commitnumber': '523cbb7',
         'molecule': {'co2': 0.0004},
         'tsfc': 300}
        ]
