
def params():
    '''
    Returns the input parameter dictionaries
    of past lblnew-overlap runs.
    '''
    return [{'commitnumber': '5014a19',
             'molecule': {'h2o': 'atmpro', 'co2': 400e-6, 'n2o': 3.2e-7},
             'band': '3a',
             'nv': 1000,
             'dv': .001,
             'atmpro': 'mls',
             'tsfc': 294},
            {'commitnumber': '5014a19',
             'molecule': {'h2o': 'atmpro', 'co2': 400e-6},
             'band': '3b',
             'nv': 1000,
             'dv': .001,
             'atmpro': 'mls',
             'tsfc': 294},
            {'commitnumber': '5014a19',
             'molecule': {'h2o': 'atmpro', 'co2': 400e-6},
             'band': '3c',
             'nv': 1000,
             'dv': .001,
             'atmpro': 'mls',
             'tsfc': 294},
            {'commitnumber': '5014a19',
             'molecule': {'h2o': 'atmpro', 'co2': 400e-6},
             'band': '4',
             'nv': 1000,
             'dv': .001,
             'atmpro': 'mls',
             'tsfc': 294},
            {'commitnumber': '5014a19',
             'molecule': {'h2o': 'atmpro', 'co2': 400e-6, 'o3': 'atmpro'},
             'band': '5',
             'nv': 1000,
             'dv': .001,
             'atmpro': 'mls',
             'tsfc': 294},
            {'commitnumber': '5014a19',
             'molecule': {'h2o': 'atmpro', 'o3': 'atmpro'},
             'band': '5',
             'nv': 1000,
             'dv': .001,
             'atmpro': 'mls',
             'tsfc': 294},
            {'commitnumber': '5014a19',
             'molecule': {'h2o': 'atmpro', 'n2o': 3.2e-7},
             'band': '7',
             'nv': 1000,
             'dv': .001,
             'atmpro': 'mls',
             'tsfc': 294},
            {'commitnumber': '5014a19',
             'molecule': {'h2o': 'atmpro', 'n2o': 3.2e-7, 'ch4': 1.8e-6},
             'band': '7',
             'nv': 1000,
             'dv': .001,
             'atmpro': 'mls',
             'tsfc': 294},
            {'commitnumber': '5014a19',
             'molecule': {'h2o': 'atmpro', 'co2': 400e-6},
             'band': '9',
             'nv': 1000,
             'dv': .001,
             'atmpro': 'mls',
             'tsfc': 294}]
