
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/00_params.ipynb

from climatools.parameters import *

class LBLnewBestfitSWParam(LBLnewParam):
    model_name = 'lblnew-bestfit-sw'
    def __init__(self, vmin=None, vmax=None,
                 conc=None,
                 ref_pts=None, ng_refs=None, ng_adju=None, klin=None, wgt=None,
                 cosz=None, rsfc=None,
                 option_k_lookup=None, **kwargs):
        super().__init__(**kwargs)
        self.vmin, self.vmax = vmin, vmax
        self.conc = conc
        self.ref_pts, self.ng_refs, self.ng_adju = ref_pts, ng_refs, ng_adju
        self.wgt = wgt
        self.cosz, self.rsfc = cosz, rsfc
        self.klin = klin
        self.option_k_lookup = option_k_lookup

    def __repr__(self):
        return '\n'.join([f"{self.__class__}", str(vars(self))])