
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/04_modeldata.ipynb

from pymongo import *
from exp.nb_00 import *
from exp.nb_01 import *
from exp.nb_02 import *

class LBLnewBestfitSWModelData():
    def __init__(self, param, wgt_flux, wgt_heat, crd_flux, crd_heat):
        self.param = param
        self.wgt_flux, self.wgt_heat = wgt_flux, wgt_heat
        self.crd_flux, self.crd_heat = crd_flux, crd_heat

    @classmethod
    def from_runner(cls, runner):
        df = pd.read_csv(runner.path/'output_flux.dat', sep=r'\s+')
        df.drop(['level'], axis=1, inplace=True)
        df.set_index(['pressure', 'g'], inplace=True)
        wgt_flux = xr.Dataset.from_dataframe(df[['wgt_flux']]).rename({'wgt_flux':'fldg'})
        crd_flux = xr.Dataset.from_dataframe(df[['crd_flux']]).rename({'crd_flux':'fldg'})

        df = pd.read_csv(runner.path/'output_heat.dat', sep=r'\s+')
        df.drop(['layer'], axis=1, inplace=True)
        df.set_index(['pressure', 'g'], inplace=True)
        wgt_heat = xr.Dataset.from_dataframe(df[['wgt_heat']]).rename({'wgt_heat':'heatrg'})
        crd_heat = xr.Dataset.from_dataframe(df[['crd_heat']]).rename({'crd_heat':'heatrg'})
        return cls(runner.param, wgt_flux, wgt_heat, crd_flux, crd_heat)

    def from_mongodoc(self, doc):
        pass