
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/01_lblnew-bestfit-sw_setup.ipynb

from pathlib import *

# This is the path to lblnew-bestfit-sw repository
SRC = Path('/chia_cluster/home/jackyu/radiation/crdnew-sw/')

# This is the path to the repository for notebooks associated with lblnew-bestfit-sw.
PATH_ANALYSIS = Path('/chia_cluster/home/jackyu/radiation/analysis_-_new_kdist_param_sw/')

FNAMES = ['lblnew-bestfit-sw.f', 'lblcom.f']

COMPILE_COMMAND = ("ifort -CB -g -traceback -fpe0 -warn unused -r8 "
                   "lblcom.f lblnew-bestfit-sw.f -o lblnew-bestfit-sw.exe")